/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"
#import "TAsyncTransport.h"
#import "TProtocolFactory.h"
#import "TBaseClient.h"


typedef int32_t int;

@protocol MultiplicationService <NSObject>
- (int) multiply: (int) n1 n2: (int) n2;  // throws TException
@end

@interface MultiplicationServiceClient : TBaseClient <MultiplicationService> - (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface MultiplicationServiceProcessor : NSObject <TProcessor> {
  id <MultiplicationService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithMultiplicationService: (id <MultiplicationService>) service;
- (id<MultiplicationService>) service;
@end

@interface simpleConstants : NSObject {
}
@end
